### ISSUE TITLE
Use re.sub in helper.checkForVariables

### ISSUE THREAD

**Issue by phihag** [hhucn/netsec-uebungssystem#10]

**Comment by maride** [comment]
Why use `re.sub` in `helper.checkForVariables`? It's a good use for `re.findall`.

**Comment by phihag** [comment]
First of all, the function name is misleading; it doesn't check but instead replaces.

Secondly, a test case may check the result of

```
checkForVariable(collections.namedtuple('Mail', ['variables'])({'PRICE': '2$'}), '$PRICEPRICE $PRICE $PRICE $PRICEHALF')
```

Thirdly, if a variable named '""' (that's an empty string) should ever sneak in, this will cause quite a lot of havoc. (The same goes for all single-letter variable names)

I am also not sure why variable names must be upper case, and must not contain underscores or numbers.

I believe the following implementation to be far superior, having none of the aforementioned issues (i.e. passing all the test cases):

```
def checkForVariable(mail, raw):
    return re.sub(
        r'\$([a-zA-Z0-9_]+)',
        lambda m: mail.get(m.group(1), m.group(0)), raw)
```
